title: Shan Guang_FF
author: LinYi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here's to books,the cheapest vacation you can buy.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
